// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data.EF.Store;

#nullable disable

namespace Store.Data.EF.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250331082540_AREYOUSURE")]
    partial class AREYOUSURE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Data.BookDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(305)
                        .HasColumnType("nvarchar(305)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "D. Adams",
                            Description = "A comedic journey through space with a towel and a lot of absurdity.",
                            Isbn = "ISBN 12345-67890",
                            Price = 42.00m,
                            Title = "The Hitchhiker’s Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 2,
                            Author = "G. Orwell",
                            Description = "Big Brother is watching you. A dystopian classic about surveillance.",
                            Isbn = "ISBN 98765-43210",
                            Price = 19.84m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "A. Hitler",
                            Description = "A controversial and ironic addition for historical infamy.",
                            Isbn = "ISBN 55555-66666",
                            Price = 14.88m,
                            Title = "Mein Kampf"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.K. Rowling",
                            Description = "A boy wizard discovers magic, broomsticks, and capitalism.",
                            Isbn = "ISBN 11111-22222",
                            Price = 25.99m,
                            Title = "Harry Potter and the Philosopher’s Stone"
                        },
                        new
                        {
                            Id = 5,
                            Author = "S. King",
                            Description = "A writer goes mad in a haunted hotel. Redrum!",
                            Isbn = "ISBN 77777-88888",
                            Price = 31.50m,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 6,
                            Author = "E.L. James",
                            Description = "A book that’s somehow both spicy and a punishment to read.",
                            Isbn = "ISBN 44444-33333",
                            Price = 9.99m,
                            Title = "Fifty Shades of Grey"
                        },
                        new
                        {
                            Id = 7,
                            Author = "R. Dahl",
                            Description = "A genius girl with telekinesis fights back against tyranny.",
                            Isbn = "ISBN 99999-00000",
                            Price = 12.75m,
                            Title = "Matilda"
                        },
                        new
                        {
                            Id = 8,
                            Author = "T. Pratchett",
                            Description = "An angel and demon team up to stop the apocalypse. Hilarious.",
                            Isbn = "ISBN 22222-11111",
                            Price = 18.30m,
                            Title = "Good Omens"
                        },
                        new
                        {
                            Id = 9,
                            Author = "F. Kafka",
                            Description = "Man wakes up as a bug. Life gets weirder from there.",
                            Isbn = "ISBN 66666-77777",
                            Price = 15.50m,
                            Title = "The Metamorphosis"
                        },
                        new
                        {
                            Id = 10,
                            Author = "M. Twain",
                            Description = "A boy’s mischievous adventures in a simpler, yet chaotic time.",
                            Isbn = "ISBN 88888-99999",
                            Price = 22.75m,
                            Title = "The Adventures of Tom Sawyer"
                        },
                        new
                        {
                            Id = 11,
                            Author = "L. Carroll",
                            Description = "A girl falls into a rabbit hole of nonsense and tea parties.",
                            Isbn = "ISBN 33333-44444",
                            Price = 17.20m,
                            Title = "Alice’s Adventures in Wonderland"
                        },
                        new
                        {
                            Id = 12,
                            Author = "V. Nabokov",
                            Description = "A disturbing yet beautifully written tale of obsession.",
                            Isbn = "ISBN 55555-99999",
                            Price = 23.80m,
                            Title = "Lolita"
                        },
                        new
                        {
                            Id = 13,
                            Author = "J.R.R. Tolkien",
                            Description = "One ring to rule them all. Hobbits, elves, and epic battles.",
                            Isbn = "ISBN 77777-11111",
                            Price = 35.00m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 14,
                            Author = "H. Melville",
                            Description = "A man vs. a whale. Spoiler: the whale wins.",
                            Isbn = "ISBN 22222-55555",
                            Price = 29.95m,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 15,
                            Author = "D. Brown",
                            Description = "Conspiracy, art, and a lot of running around Europe.",
                            Isbn = "ISBN 99999-22222",
                            Price = 26.30m,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 16,
                            Author = "A. Rand",
                            Description = "Capitalism’s Bible, or a really long lecture—your choice.",
                            Isbn = "ISBN 44444-66666",
                            Price = 39.10m,
                            Title = "Atlas Shrugged"
                        },
                        new
                        {
                            Id = 17,
                            Author = "N. Gogol",
                            Description = "A man buys dead peasants. Russian satire at its finest.",
                            Isbn = "ISBN 11111-77777",
                            Price = 21.90m,
                            Title = "Dead Souls"
                        },
                        new
                        {
                            Id = 18,
                            Author = "C. Palahniuk",
                            Description = "The first rule: don’t talk about it. Oops.",
                            Isbn = "ISBN 88888-33333",
                            Price = 27.25m,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 19,
                            Author = "J. Austen",
                            Description = "Love, snark, and Regency-era drama.",
                            Isbn = "ISBN 66666-44444",
                            Price = 14.50m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 20,
                            Author = "K. Marx",
                            Description = "Workers unite! A short book with big ideas.",
                            Isbn = "ISBN 33333-88888",
                            Price = 5.80m,
                            Title = "The Communist Manifesto"
                        },
                        new
                        {
                            Id = 21,
                            Author = "H.P. Lovecraft",
                            Description = "Cosmic horror with tentacles. Sweet dreams!",
                            Isbn = "ISBN 55555-22222",
                            Price = 13.00m,
                            Title = "The Call of Cthulhu"
                        },
                        new
                        {
                            Id = 22,
                            Author = "E. Hemingway",
                            Description = "An old man fights a fish. It’s deeper than it sounds.",
                            Isbn = "ISBN 99999-55555",
                            Price = 16.30m,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 23,
                            Author = "A. Camus",
                            Description = "Life is absurd, and so is this guy’s trial.",
                            Isbn = "ISBN 77777-33333",
                            Price = 18.60m,
                            Title = "The Stranger"
                        },
                        new
                        {
                            Id = 24,
                            Author = "R. Bradbury",
                            Description = "Books burn at 451°F. A warning about censorship.",
                            Isbn = "ISBN 22222-99999",
                            Price = 20.20m,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 25,
                            Author = "W. Shakespeare",
                            Description = "To be or not to be—ghosts, revenge, and skulls.",
                            Isbn = "ISBN 11111-66666",
                            Price = 11.90m,
                            Title = "Hamlet"
                        },
                        new
                        {
                            Id = 26,
                            Author = "T. Morrison",
                            Description = "A haunting tale of slavery’s aftermath.",
                            Isbn = "ISBN 88888-44444",
                            Price = 24.75m,
                            Title = "Beloved"
                        },
                        new
                        {
                            Id = 27,
                            Author = "J. Swift",
                            Description = "Tiny people, giants, and a horse society. Satire galore.",
                            Isbn = "ISBN 66666-55555",
                            Price = 15.90m,
                            Title = "Gulliver’s Travels"
                        },
                        new
                        {
                            Id = 28,
                            Author = "M. Shelley",
                            Description = "A scientist plays God, and it goes about as well as you’d expect.",
                            Isbn = "ISBN 33333-99999",
                            Price = 17.40m,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 29,
                            Author = "P. Coelho",
                            Description = "Follow your dreams, find treasure, and overthink everything.",
                            Isbn = "ISBN 55555-11111",
                            Price = 19.15m,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 30,
                            Author = "D. Trump",
                            Description = "Bigly business advice from a guy with gold hair.",
                            Isbn = "ISBN 99999-77777",
                            Price = 45.60m,
                            Title = "The Art of the Deal"
                        });
                });

            modelBuilder.Entity("Store.Data.OrderDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DeliveryAmount")
                        .HasColumnType("money");

                    b.Property<string>("DeliveryCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DeliveryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.Data.OrderItemDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Store.Data.OrderItemDto", b =>
                {
                    b.HasOne("Store.Data.OrderDto", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Store.Data.OrderDto", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
